### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by R1N4x** [corb3000/ha-artnet-led#5]
I'm running 2021.12.9

And got this: 

`Entity light.my_dimmer (<class 'custom_components.artnet_led.light.ArtnetDimmer'>) implements device_state_attributes. Please report it to the custom component author.`

Anything I can do about it? 

Lamps don't appear anywhere in HA but I can control them in the Alexa app.

**Comment by Breina** [comment]
That warning is fixed in #7
