### ISSUE TITLE
Lights goes off when restarting HA.

### ISSUE THREAD

**Issue by methosmen** [corb3000/ha-artnet-led#6]
Anytime I do a restart of HA. The lights in this integration goes to 00.
Would really appreciate to have the lights stay at their state before restart.

**Comment by Breina** [comment]
Yeah, my wife complains about this too. Should be possible to just read the DMX state on startup.

To elaborate, the lights stay on a short while after HA is up until it decides to 'refresh' the lights' state. The bug fix would be to read the state from DMX and to write that to HA upon initialization of the plugin.

**Comment by mvandenabeele** [comment]
I have a PR that fixes this issue. I hope it'll be merged soon, so I can switch back to the 'official' branch.

**Comment by Breina** [comment]
#3 

@corb3000 Please click the button 😗

**Comment by corb3000** [comment]
Fixed by mvandenabeele
